export const data = [
  {
    id: "feb-9",
    day: "Tue",
    date: 9,
    fullDate: "February 9 @ 8:00 am - 5:00 pm",
    title: "Title (link to individual page)",
    location: "Location (Link to google maps page??",
    description: "Description (excerpt)",
  },
  {
    id: "mar-10",
    day: "Wed",
    date: 10,
    fullDate: "March 10 @ 8:00 am - 5:00 pm",
    title: "Title (link to individual page)",
    location: "Location (Link to google maps page??",
    description: "Description (excerpt)",
  },
  {
    id: "mar-12",
    day: "Fri",
    date: 12,
    fullDate: "March 12 @ 8:00 am - 5:00 pm",
    title: "Title (link to individual page)",
    location: "Location (Link to google maps page??",
    description: "Description (excerpt)",
  },
  {
    id: "apr-9",
    day: "Fri",
    date: 9,
    fullDate: "April 9 @ 8:00 am - 5:00 pm",
    title: "Title (link to individual page)",
    location: "Location (Link to google maps page??",
    description: "Description (excerpt)",
  },
];
